[package]
name = "simple_kbuckets"
version = "0.1.0"
authors = ["Valentin Lorentz <progval+git@progval.net>"]
description = "Simple implementation of a Kademlia-like hash table."
license = "MIT"
repository = "https://github.com/rust-fcp/rust-fcp-switching"
readme = "README.md"

[dependencies]
